# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='photo',
            field=models.FileField(upload_to=''),
        ),
    ]
