# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170407_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='username',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='room_id',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='owner',
            new_name='user',
        ),
    ]
