# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170408_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='country',
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.FloatField(verbose_name='Price'),
        ),
    ]
