# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170410_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(max_length=255, verbose_name='Type of Room'),
        ),
    ]
