# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170416_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='age',
        ),
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.FileField(default='settings.MEDIA_ROOT/default/avatar.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='ac',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='desc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='room',
            name='furnitured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='kitchen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='no_bedrooms',
            field=models.IntegerField(default=0, verbose_name='no.of bed rooms'),
        ),
        migrations.AddField(
            model_name='room',
            name='no_beds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='pets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='home_town',
            field=models.CharField(default='', max_length=100, verbose_name='Home Town'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='room',
            name='Zipcode',
            field=models.CharField(default='', max_length=20, verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='room',
            name='avgrating',
            field=models.IntegerField(default=0, verbose_name='Average Rating'),
        ),
        migrations.AlterField(
            model_name='room',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='room',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='room',
            name='state',
            field=models.CharField(default='', max_length=100, verbose_name='State'),
        ),
    ]
