# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170417_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.FileField(default='/default/avatar.png', upload_to=''),
        ),
    ]
