# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20170417_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='guest',
            field=models.IntegerField(default=1, verbose_name='no.of guests'),
        ),
        migrations.AlterField(
            model_name='room',
            name='no_bedrooms',
            field=models.IntegerField(default=1, verbose_name='no.of bed rooms'),
        ),
        migrations.AlterField(
            model_name='room',
            name='no_beds',
            field=models.IntegerField(default=1),
        ),
    ]
