# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20170417_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='userDetails',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.Person'),
        ),
    ]
