# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 23:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20170417_0342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='userDetails',
            new_name='Person',
        ),
    ]
