# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20170417_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='title',
            field=models.CharField(default='hey there', max_length=255),
        ),
    ]
