# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20170418_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='photo',
            field=models.FileField(upload_to='/media/room/'),
        ),
    ]
