# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20170418_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='service',
            field=models.IntegerField(default=0),
        ),
    ]
